perl	SLURM_GENERATOR_BWA.pl	301
perl	SLURM_GENERATOR_BWA.pl	302
perl	SLURM_GENERATOR_BWA.pl	303
perl	SLURM_GENERATOR_BWA.pl	304
perl	SLURM_GENERATOR_BWA.pl	305
perl	SLURM_GENERATOR_BWA.pl	306
perl	SLURM_GENERATOR_BWA.pl	307
perl	SLURM_GENERATOR_BWA.pl	308
perl	SLURM_GENERATOR_BWA.pl	310
perl	SLURM_GENERATOR_BWA.pl	312
perl	SLURM_GENERATOR_BWA.pl	313
perl	SLURM_GENERATOR_BWA.pl	314
perl	SLURM_GENERATOR_BWA.pl	315
perl	SLURM_GENERATOR_BWA.pl	316
perl	SLURM_GENERATOR_BWA.pl	318
perl	SLURM_GENERATOR_BWA.pl	319
perl	SLURM_GENERATOR_BWA.pl	320

